# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Matrix Trace
#'
#' Calculates the trace of a matrix \eqn{A}.
#'
#' @param A Numeric matrix.
#' @return Scalar. 
tr <- function(A) {
    .Call('_Temporal_tr', PACKAGE = 'Temporal', A)
}

#' Matrix Matrix Product
#'
#' Calculates the product \eqn{AB}. 
#'
#' @param A Numeric matrix.
#' @param B Numeric matrix.
#' @return Numeric matrix. 
fastMMp <- function(A, B) {
    .Call('_Temporal_fastMMp', PACKAGE = 'Temporal', A, B)
}

#' Matrix Transpose
#'
#' Constructs \eqn{A'} from \eqn{A}.
#'
#' @param A Numeric matrix.
#' @return Numeric matrix.
fastT <- function(A) {
    .Call('_Temporal_fastT', PACKAGE = 'Temporal', A)
}

#' Matrix Inner Product
#'
#' Calculates the product \eqn{A'B}.
#'
#' @param A Numeric matrix.
#' @param B Numeric matrix.
#' @return Numeric matrix. 
fastIP <- function(A, B) {
    .Call('_Temporal_fastIP', PACKAGE = 'Temporal', A, B)
}

#' Matrix Inverse
#' 
#' Calcualtes \eqn{A^{-1}}.
#'
#' @param A Numeric matrix.
#' @return Numeric matrix. 
fastInv <- function(A) {
    .Call('_Temporal_fastInv', PACKAGE = 'Temporal', A)
}

#' Matrix Determinant
#'
#' Calculates the determinant of \eqn{A}.
#'
#' @param A Numeric matrix.
#' @return Scalar. 
fastDet <- function(A) {
    .Call('_Temporal_fastDet', PACKAGE = 'Temporal', A)
}

#' Quadratic Form
#' 
#' Calculates the quadratic form \eqn{X'AX}.
#' 
#' @param X Numeric matrix.
#' @param A Numeric matrix.
#' @return Numeric matrix.
fastQF <- function(X, A) {
    .Call('_Temporal_fastQF', PACKAGE = 'Temporal', X, A)
}

#' Schur complement
#'
#' Calculates the efficient information \eqn{I_{11}-I_{12}I_{22}^{-1}I_{21}}. 
#'
#' @param I11 Information of target parameter
#' @param I22 Information of nuisance parameter
#' @param I12 Cross information between target and nuisance parameters
#' @return Numeric matrix. 
#'
SchurC <- function(I11, I22, I12) {
    .Call('_Temporal_SchurC', PACKAGE = 'Temporal', I11, I22, I12)
}

